site_name: .fmbot
repo_url: https://github.com/fmbot-discord/fmbot
repo_name: fmbot
site_description: Welcome to .fmbot! .fmbot is a social Discord bot that provides music statistics for you, your friends, and your fellow server members.
theme:
  name: 'material'
  custom_dir: docs/overrides
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: img/logo.png
  favicon: img/favicon.png
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true

extra_javascript:
  - javascript/analytics.js

extra_css:
  - style/style.css

edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fmbotDiscord
copyright: .fmbot is not affiliated with Last.fm

nav:
  - 'Introduction': 'index.md'
  - 'Frequently Asked Questions': 'faq.md'
  - 'Commands':
    - 'Getting started': 'commands/index.md'
    - 'Albums': 'commands/albums.md'
    - 'Artists': 'commands/artists.md'
    - 'Countries': 'commands/countries.md'
    - 'Crowns': 'commands/crowns.md'
    - 'Featured': 'commands/featured.md'
    - 'Friends': 'commands/friends.md'
    - 'Genius': 'commands/genius.md'
    - 'Genres': 'commands/genres.md'
    - 'Plays': 'commands/plays.md'
    - 'Spotify': 'commands/spotify.md'
    - 'Tracks': 'commands/tracks.md'
    - 'Updating and indexing': 'commands/whoknows.md'
    - 'YouTube': 'commands/youtube.md'
    - 'Miscellaneous': 'commands/misc.md'
  - 'Server settings':
    - 'General': 'guildsettings/index.md'
    - 'WhoKnows': 'guildsettings/whoknowsettings.md'
    - 'Crowns': 'guildsettings/crownsettings.md'
    - 'Webhooks': 'guildsettings/webhooks.md'
  - 'Music bot scrobbling': 'botscrobbling.md'
  - 'Development': 'setup.md'
  - 'Privacy': 'privacy.md'
  - 'Terms of Service': 'terms.md'
  - 'Get .fmbot supporter': 'supporter.md'
  - 'Join our server': http://server.fmbot.xyz/
  - 'Invite the bot': http://invite.fmbot.xyz/
